version: '3.8'

services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: 'nutrichat_postgres'
    environment:
      - 'POSTGRES_DB=nutri'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    labels:
      - 'org.springframework.boot.service-connection=postgres'
    ports:
      - '5432:5432'

    volumes:
      - './db/init:/docker-entrypoint-initdb.d'
volumes:
  postgres_data: