version: '3.9'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: nutrichat_postgres
    environment:
      POSTGRES_DB: nutri
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/init:/docker-entrypoint-initdb.d

  backend:
    build: .
    container_name: nutrichat_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nutri
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
