spring:
  application:
    name: nutrichat

  datasource:
    url: jdbc:postgresql://localhost:5432/nutri
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
  ai:
    openai:
      api-key: ""

    ollama:
      embedding:
        model: 'nomic-embed-text'
      chat:
        model: 'phi'
        enabled: false
    gemini:
      chat:
        model: gemini-2.5-flash # ⬅️ Modelo rápido e eficiente para Chat
      # 2. Configuração da API Key (o Spring a buscará da Variável de Ambiente)
      api:
        api-key: ${GEMINI_API_KEY}

    model:
      chat: 'google-genai'

    google:
      genai:
        api-key: ${GEMINI_API_KEY}

  vectorstore:
    pgvector:
      dimensions: 768
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      max-document-batch-size: 10000

  docker:
    compose:
      file: 'compose.yml'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.function.context.FunctionCatalogAutoConfiguration'
      - 'org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration'

