spring:
  application:
    name: nutrichat
  profiles:
    # Tenta carregar o valor da ENV VAR SCOPE.
    # Se SCOPE n√£o estiver definido, usa 'default' ou 'dev' como fallback (opcional).
    active: ${SCOPE:default}
  datasource:
    url: jdbc:postgresql://localhost:5432/nutri
    username: postgres
    password: postgres

  ai:
    openai:
      api-key: ${OPEN_API_KEY}
      chat:
        options:
          model: gpt-4

  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimensions: 1536
    max-document-batch-size: 10000

  docker:
    compose:
      file: 'compose.yml'
  autoconfigure:
    exclude: 'org.springframework.cloud.function.context.FunctionCatalogAutoConfiguration'